### ISSUE TITLE
[Feature] provide the option to run all scenarios or a given scenario

### ISSUE THREAD

**Issue by cloudnull** [ansible-community/pytest-molecule#1]
I have a very similar, yet slightly different, use-case and would love to use this plugin instead of having to carry code within the TripleO-Ansible project. 

##### This is the code we're currently using to execute molecule tests using `pytests`. 
* https://github.com/openstack/tripleo-ansible/tree/master/tests

This simple test runner will allow us to define a given scenario as needed. In the event that no scenario is defined, the runner will execute all scenarios found within a given role. 

The test runner used in tripleo-ansible was created because we're testing every role in isolation. In the event that a given role has more than one scenario to test, the role will have multiple tox entries making it possible for the developer to easily test any scenario as needed.

It would be great if we could have this plugin could provide an option to set a test scenario and potentially special case an `_all_` option which will use the `--all` switch in molecule.

**Comment by ssbarnea** [comment]
I propose that the default behavior would be to run all scenarios but not using `molecule --all` but instead by running one separated pytest for each of them.

**Comment by cloudnull** [comment]
The reason we're running with the ``--all`` flag at this time is so that we're generating a single HTML report at the end of the test run. So long as we can ensure we're not impacting the pytest report I think its fine to run each scenario one by one.

**Comment by ssbarnea** [comment]
I am going to close this because this is already supported. By default molecule will run all scenarios discovered, each of them will be run as an individual pytest. The final report includes output from all of them.

If the user wants to run only one scenario, he can call pytest with that individual molecule file as parameter. For example `pytest tests/roles/myrole/molecule/default/molecule.yml`

**Comment by cloudnull** [comment]
Please consider re-opening this issue, As a developer I need to be able to run a specific scenario for a given role and then all scenarios for that one role; not all scenarios across all roles discovered by the plugin. By default molecule will only run the "default" scenario when executing `molecule test`. We have to pass in the "--all" flag for it to run all the scenarios from within that role.

If we're to adopt this plugin we'll need the ability to target both roles and scenarios.

**Comment by ssbarnea** [comment]
Maybe you missed to observe it but pytest-molecule calls molecule for all detected scenarios, each scenario is detected as an individual test.

Due to this there is no need to call molecule with —all as we already loop on each pf them.

It is true that currently we do not pass extra params but feel free to make a new feature. request for that, preferably a PR too.
