### ISSUE TITLE
Decouple pytest-molecule from ansible package

### ISSUE THREAD

**Issue by yajo** [ansible-community/pytest-molecule#85]
AFAICS molecule itself now allows to use ansible-base: https://github.com/ansible-community/molecule/pull/2805

However, installing pytest-molecule installs the full ansible distribution.

IMHO this package should reflect upstream's decision.

**Comment by ssbarnea** [comment]
In fact is even more than this, take a look at https://github.com/ansible-community/molecule/pull/2926 -- Molecule 3.2 no longer needs Ansible installed inside the same python interpreter. This means that we need to update pytest-molecule to prevent it from bringing Ansible as a dependency too.

There is a list of molecule related projects that need the same type of change for decoupling from Ansible python package.

If you can make a PR to do it it would be great.

**Comment by ssbarnea** [comment]
It may seem weird but this bug is not on pytest-molecule, is in fact a molecule bug regarding how its extras are configured, mainly because `test` extra includes ansible and ansible-lint, which it should not. They should be installed by ansilbe and lint extras. Test extra should be limited to install only testing tools for molecule itself and its extensions and deliberately avoid dragging ansible in by accident.
